spring.application.name=painel-servidor

server.port=${PORT:8080}

# =========================================================
# CONFIGURAÇÃO DO POSTGRESQL (RENDER)
# =========================================================
# Cole o 'External Database URL' do Render aqui (certifique-se de manter o ?sslmode=require no final)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://COLE_O_HOST_AQUI:5432/COLE_O_DATABASE_AQUI?sslmode=require}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:COLE_O_USERNAME_AQUI}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:COLE_A_PASSWORD_AQUI}

# =========================================================
# CONFIGURAÇÕES DE JPA / HIBERNATE
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true

# =========================================================
# SEGURANÇA E JWT
# =========================================================
api.security.token.secret=${JWT_SECRET:c3A4bDk2RjlzYTg3RDIzT1A1NjhBNzkxMlpYQ1ZCTk0xMjM0NTY3ODkwUVdFUlRZVUlPUCAxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUA}
api.security.token.expiration-hours=24