spring.application.name=painel-servidor

server.port=${PORT:8080}

# =========================================================
# CONFIGURAÇÃO DO POSTGRESQL COM VARIÁVEIS DE AMBIENTE
# =========================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-xxxxxxxxx-a.oregon-postgres.render.com:5432/paineldb_xxxx?sslmode=require}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:paineldb_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sua_senha_copiada_do_render}

# =========================================================
# CONFIGURAÇÕES DE JPA / HIBERNATE
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true

# =========================================================
# SEGURANÇA E JWT
# =========================================================
api.security.token.secret=${JWT_SECRET:c3A4bDk2RjlzYTg3RDIzT1A1NjhBNzkxMlpYQ1ZCTk0xMjM0NTY3ODkwUVdFUlRZVUlPUCAxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUA}
api.security.token.expiration-hours=24
