# ===================================================================
# CONFIGURAÇÕES DA APLICAÇÃO
# ===================================================================
spring.application.name=painel-servidor
server.port=8080

# ===================================================================
# BANCO DE DADOS H2 (Banco em memória para Testes e Desenvolvimento)
# ===================================================================
# Para usar MySQL/PostgreSQL em produção, altere o driver e a URL.
spring.datasource.url=jdbc:h2:mem:paineldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=rooto

# Habilita o console web do H2 para visualizar as tabelas no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# JPA / HIBERNATE
# ===================================================================
# 'update' cria ou atualiza as tabelas no banco automaticamente com base nas Entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===================================================================
# VARIÁVEIS DO JWT (JSON Web Token)
# ===================================================================
# Chave secreta para assinar o token (altere para uma chave longa e segura em produção)
# Chave secreta (deve ter no mínimo 64 caracteres para o algoritmo HS512)
# Substitua a chave antiga por esta (com 80 caracteres/bytes):
api.security.token.secret=c3A4bDk2RjlzYTg3RDIzT1A1NjhBNzkxMlpYQ1ZCTk0xMjM0NTY3ODkwUVdFUlRZVUlPUCAxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUA
# Tempo de expiração em horas
api.security.token.expiration-hours=24




spring.jpa.defer-datasource-initialization=true